local Config = {
	KISS_COOLDOWN = 0.8,
	COMBO_WINDOW = 3,
	SUPER_KISS_CHANCE = 0.02,
	BASE_KISS_COINS = 10,
	PROXIMITY_RANGE = 10,
	LEADERBOARD_UPDATE_INTERVAL = 30,
	MILESTONE_INTERVAL = 100,
	AUTO_SAVE_INTERVAL = 60,
	RATE_LIMIT_MAX = 20,
	RATE_LIMIT_WINDOW = 10,
	DEBUG_MODE = false,
}

return Config
